spring:
  datasource:
    url: jdbc:mysql://49.234.109.24:3306/logindemo?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: Th19981008..
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    port: 6379

  rabbitmq:
    host: 49.234.109.24
    username: admin
    password: 123456
    port: 5672
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8081
